test_railcars:
	ruby tests/test_railcar_cargo.rb
	ruby tests/test_railcar_passenger.rb

test_train:
	ruby tests/test_train.rb
test_trains:
	ruby tests/test_train.rb
	ruby tests/test_train_cargo.rb
	ruby tests/test_train_passenger.rb

test_route:
	ruby tests/test_route.rb

test_station:
	ruby tests/test_station.rb

test_module_instance_counter:
	ruby tests/test_module_instance_counter.rb
